app/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/(?P<weight>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^clear$', views.cart_clear, name='cart_clear'),
]

app/opeshek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('cart', include(arg='cart.urls', namespace='cart')),
    path('orders', include(arg='orders.urls', namespace='orders')),
    path('landing', include(arg='landing.urls', namespace='landing')),
    path('', include(arg='shop.urls', namespace='shop')),
]

app/orders/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^pay/(?P<order_id>[0-9a-z-]+)/$', views.order_pay, name='order_pay'),
    url(r'^fail/$', csrf_exempt(views.order_fail), name='order_fail'),
    url(r'^success/$', csrf_exempt(views.order_success), name='order_success'),
    url(r'^callback/$', csrf_exempt(views.order_callback), name='order_callback'),
]

app/cart/models.py
from django.db import models

# Create your models here.

app/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    weight = forms.IntegerField(required=True)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

app/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 weight=cd['weight'],
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return JsonResponse({
        'total_price': cart.get_total_price(),
        'count_products': cart.get_total_product()
    })


def cart_remove(request, product_id, weight):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product, weight)
    return redirect('cart:cart_detail')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

app/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load custom_filters %}

{% block head %}
    <title>Мои покупки - Opeshek.ru</title>
    <meta name="description" content="" />
{% endblock %}

{% block body %}

    <div class="main_block">
        <div class="container">
            <div class="headline">
                <h1 class="title">Корзина заказа</h1>
            </div>
            <div class="error_confirm hide">
                <p>Минимальный заказ - 700 руб.</p>
            </div>

            {% if cart|length > 0 %}
                <div class="table_checout table_cart_prod " style="max-width: 1050px;margin: auto;">
                    <table>
                        {% for item in cart %}
                            <tr id="c_row_del_239" class="tr_prod">
                                <td style="width: 25%;">
                                    <div class="image">
                                        {% if item.product.image %}
                                            <a href="{{ item.product.get_absolute_url }}">
                                                <img src="{{ item.product.image.url }}" alt="" style="max-width:50px">
                                            </a>
                                        {% endif %}
                                    </div>
                                    <div class="name">
                                        <a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a>
                                    </div>
                                </td>
                                <td style="width: 25%;">
                                    <div class="name_collum">Фасовка</div>
                                    <div class="price_itogo" style="font-weight: bold;padding:6px 0">{{ item.weight | weight }}</div>
                                </td>
                                <td class="" style="width: 25%;">
                                    <div class="name_collum" style="padding-bottom: 7px;">Кол-во</div>
                                    <div class="price_itogo" style="font-weight: bold;padding:6px 0">
                                        {{ item.quantity }}
                                    </div>
                                </td>
                                <td style="width: 25%;min-width: 54px">
                                    <div class="name_collum">Итого:</div>
                                    <div class="price_itogo" style="padding:6px 0">
                                        <strong class="prod_price_cart">{{ item.total_price }}</strong> руб.
                                    </div>
                                    <a href="{% url 'cart:cart_remove' product_id=item.product.id weight=item.weight %}" class="close black_radius">Удалить</a>
                                </td>
                            </tr>
                        {% endfor %}
                        <!--<tr id="c_row_del_163" class="tr_prod hide">
                            <td style="width: 25%;">
                                <div class="image">
                                    <img src="/images/products/kraft-paket-s-ruchkami-small.jpg" alt="" style="max-width:50px">
                                </div>
                                <div class="name">
                                    Крафт пакет с ручками
                                </div>
                            </td>
                            <td style="width: 25%;">

                                <div class="name_collum"></div>
                                <div class="price_itogo" style="font-weight: bold;padding:6px 0">
                                </div>
                            </td>
                            <td class="" style="width: 25%;">
                                <div class="name_collum" style="padding-bottom: 7px;">Кол-во</div>
                                <div class="price_itogo">
                                    <input type="hidden" class="count_cart_input" data-id="163" data-packid="0" value="1" />
                                    <select id="prod_table_cart_163_0" class=" select_single select_count_cart" style="width: 100%;" data-packid="0" data-id="163">
                                    </select>

                                </div>
                            </td>
                            <td style="width: 25%;min-width: 54px">
                                <div class="name_collum">Итого:</div>
                                <div class="price_itogo" style="padding:6px 0">
                                    <strong class="prod_price_cart">17</strong> руб.
                                    <input type="hidden" id="price_craft" value="17" />
                                </div>

                                <button type="button" class="close black_radius" data-toggle="modal" data-packid="0" data-id="163" data-target=".modal-sm"></button>
                            </td>
                        </tr>-->
                    </table>
                </div>

                <!--<div class="block_add_kraft " style="max-width: 1050px;margin: auto;color: #777;">
                    <div class="row_field clearfix" style="float: left;margin-top:15px">
                        <div class="wrap_input" style="padding-left: 2px;">
                            <input type="checkbox" style="width: 26px;height: 26px;float: left;margin-right: 12px;" name="add_craft" id="add_craft" value="1" />
                            <label for="add_craft" style="padding-top: 4px; display: inline-block;" class="label">Я хочу купить <span
                                    class="link_kraft">"<a href="/craft-packets/#craft" style="color:#777;text-decoration: underline;"
                                                           target="_blank">Крафт пакет<span> с ручками</span></a>"</span></label>
                        </div>
                    </div>
                </div>-->

                <div class="itogo_cart ">
                    Итого: <strong class="total_price_r">{{ cart.get_total_price }}</strong> руб.
                    <input type="hidden" id="total_price_check" class="total_price_r_inp" value="1000" />
                </div>
                <div class="basket_modal cart_page ">
                    <button type="button" class="close hide min_order" data-toggle="modal" data-target=".modal-sm5"></button>
                    <button type="button" class="close hide false_order" data-toggle="modal" data-target=".modal-sm_not_order"></button>
                    <a href="{% url 'orders:order_create' %}" class="button link_to_cart cart_page_button">Оформить заказ</a>
                    <a href="{% url 'cart:cart_clear' %}" class="remove_cart ">Очистить корзину</a>
                </div>
            {% else %}
                <p class="not_cart_prodts" style="text-align: center;"><strong>Ваша корзина пуста</strong></p>
            {% endif %}
        </div>
    </div>
{% endblock %}