app/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/(?P<weight>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^clear$', views.cart_clear, name='cart_clear'),
]

app/opeshek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('cart', include(arg='cart.urls', namespace='cart')),
    path('orders', include(arg='orders.urls', namespace='orders')),
    path('landing', include(arg='landing.urls', namespace='landing')),
    path('', include(arg='shop.urls', namespace='shop')),
]

app/shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('dostavka', views.dostavka, name='dostavka'),
    path('craft-packets', views.craftPackets, name='craft-packets'),
    path('discounts', views.discounts, name='discounts'),
    path('kak-sdelat-zakaz', views.zakaz, name='zakaz'),
    path('voprosy-i-otvety', views.questions, name='questions'),
    path('contact', views.contact, name='contact'),

    path('all-foods',
         views.product_list,
         name='product_list'),

    path('search', views.search, name='search'),

    path('<str:category_slug>',
        views.product_list,
        name='product_list_by_category'),

    path('<str:category_slug>/<str:slug>',
         views.product_detail,
         name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/shop/models.py
import os
from math import ceil

from django.db import models
from django.urls import reverse
from opeshek.storage import OverwriteStorage

from shop.utils import get_discount


def categories_path(instance, filename):
    filename, file_extension = os.path.splitext(filename)
    return 'categories/{0}{1}'.format(instance.slug, file_extension)


def products_path(instance, filename):
    filename, file_extension = os.path.splitext(filename)
    return 'products/{0}{1}'.format(instance.slug, file_extension)


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Наименование')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='Slug')
    image = models.ImageField(storage=OverwriteStorage(), upload_to=categories_path, blank=True, verbose_name='Изображение')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Наименование')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Slug')
    image = models.ImageField(storage=OverwriteStorage(), upload_to=products_path, blank=True, verbose_name='Изображение')
    description = models.TextField(blank=True, verbose_name='Описание')
    composition = models.TextField(blank=True, verbose_name='Состав')
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name='Цена за 150г')
    stock = models.PositiveIntegerField(verbose_name='В наличии')
    available = models.BooleanField(default=True, verbose_name='Доступно')
    bestseller = models.BooleanField(default=True, verbose_name='Хит-продаж')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        index_together = (('id', 'slug'),)
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.category.slug, self.slug])

    def get_short_description(self):
        if len(self.description) > 10:
            return self.description[0:10] + '...'
        return self.description

    def get_prices(self):
        return [
            { 'weight': 150, 'display': '150 г', 'price': self.get_price(150) },
            { 'weight': 300, 'display': '300 г', 'price': self.get_price(300) },
            { 'weight': 500, 'display': '500 г', 'price': self.get_price(500) },
            { 'weight': 1000, 'display': '1 кг', 'price': self.get_price(1000) }
        ]

    def get_price(self, weight):
        discount = get_discount(weight)
        price = self.price * weight / 150
        price = price - (price * discount / 100)
        return ceil(price)

    def get_first_price(self):
        return self.get_prices()[0]

app/shop/views.py
import bleach
from django.shortcuts import render, get_object_or_404
from shop.models import Category, Product
from cart.forms import CartAddProductForm


def home(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    bestsellers = Product.objects.filter(bestseller=True)

    return render(request,
                  'shop/partial/home.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'bestsellers': bestsellers})

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

def product_detail(request, category_slug, slug):
    product = get_object_or_404(Product,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                  'cart_product_form': cart_product_form})

def search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        products = Product.objects.filter(available=True, name__icontains=bleach.clean(q))
        return render(request,
                      'shop/product/search_results.html',
                      {'products': products, 'query': q})

    products = Product.objects.filter(available=True)
    return render(request,
                  'shop/product/search_results.html',
                  {'products': products})

def about(request):
    return render(request, "shop/partial/about.html")

def dostavka(request):
    return render(request, "shop/partial/dostavka.html")

def craftPackets(request):
    return render(request, "shop/partial/craft-packets.html")

def discounts(request):
    return render(request, "shop/partial/discounts.html")

def zakaz(request):
    return render(request, "shop/partial/kak-sdelat-zakaz.html")

def questions(request):
    return render(request, "shop/partial/voprosy-i-otvety.html")

def contact(request):
    return render(request, "shop/partial/contact.html")

app/shop/templates/shop/product/card.html
{% load custom_filters %}

<div class="thumb">
    <div class="th">
        <div class="title only_mobile" style="text-align: left;margin-top: 0;"><a
                class="link_name" href="{{ product.get_absolute_url }}"
                title="Купить {{ product.name }}">{{ product.name }}</a></div>
        <form action="{% url 'cart:cart_add' product.id %}" method="post" id="productForm-{{ product.id }}">
            {% csrf_token %}
            <div class="wrap_image">
                <a href="{{ product.get_absolute_url }}" class="hover_list_prod"
                   title="Купить {{ product.name }}">
                    {% if product.image %}
                        <img src="{{ product.image.url }}"
                             id="img_10"
                             alt="Купить {{ product.name }}" title="Купить {{ product.name }}">
                    {% endif %}
                </a>
            </div>
            <div class="text_data">
                <div class="title only_desctop"><a class="link_name"
                                                   href="{{ product.get_absolute_url }}"
                                                   title="Купить {{ product.name }}">{{ product.name }}</a>
                </div>
                {% if product.get_short_description %}
                    <div class="desc only_desctop">{{ product.get_short_description }}</div>
                {% endif %}
                <div class="tools">
                    <div class="fas_selectinput_box">
                        <span style="display: block;margin-bottom:4px">Фасовка</span>
                        <select name="weight" style="width: 100%;"
                                class="select_single select_pack" data-id="{{ product.id }}"
                                id="prod_pack_{{ product.id }}">
                            {% for price in product.get_prices %}
                                <option value="{{ price.weight }}">{{ price.weight | weight }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="fas_selectinput_box">
                        <span style="display: block;margin-bottom:4px">Кол-во</span>
                        <select name="quantity" class=" select_single select_count select_count_{{ product.id }}" style="width: 100%;"
                                id="quantity" data-id="{{ product.id }}"></select>
                    </div>
                    <div class="hide">
                        {% for price in product.get_prices %}
                            <span id="prod_{{ product.id }}_{{ price.weight }}">{{ price.price }}</span>
                        {% endfor %}
                    </div>
                    <input type="hidden" id="type_prod_{{ product.id }}" value="1"/>
                </div>
                <div class="bottom">
                    <button class="button checkit" type="button" data-id="{{ product.id }}">
                        <span>В Корзину</span>
                    </button>
                </div>
                <div class="price">
                    <div class="hold">
                        <input type="hidden" id="price_prod_{{ product.id }}" value="{{ product.get_first_price.price }}"/>
                        <span>
                            <em class="price_for">Цена: </em>
                            <span id="price_show_{{ product.id }}" class="price_prod">{{ product.get_first_price.price }}</span>
                            <em>руб.</em>
                        </span>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

app/shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block head %}
    <title>Купить орехи - интернет-магазин в Санкт-Петербурге (СПб) оптом и в розницу</title>
    <meta name="description" content="Вы можете купить орехи в интернет-магазине Opeshek.ru по низкой цене в СПб. Доставка по Санкт-Петербургу и Ленобласти. Мы торгуем оптом и в розницу." />
{% endblock %}

{% block body %}
    <div class="breadcrumbs">
        <div class="container">
            <ul class="breadcrumbs_list">
                <li class="item">
                    <a href="/"><span>Главная</span></a>
                </li>
                <li class="item">
                    <a href="/all-foods"><span>Интернет-магазин</span></a>
                </li>
                {% if category %}
                    <li class="item">
                        <span>{{ category.name }}</span>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>

    <div class="nav_inner">
        <div class="holder">
            <div class="item {% if not category %} selected {% endif %}">
                <a href="/all-foods">
                    <span>Все</span>
                </a>
            </div>
            {% for c in categories %}
                <div class="item {% if category.slug == c.slug %} selected {% endif %}">
                    <a href="{{ c.get_absolute_url }}">
                        <span>{{ c.name }}</span>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="main_block">
        <div class="container">
            <div class="headline mb35">
                {% if category %}
                    <h1 class="title">{{ category.name }}</h1>
                {% else %}
                    <h1 class="title">Все продукты</h1>
                {% endif %}
            </div>

            <!--<div class="filter_block clearfix">
                <div class="sort_block sb_filtr">
                    <span>Фильтр:</span>
                    <div class="select_block">
                        <span class="this_item">Все</span>
                        <div class="sb_items">
                            <a href="kupit-orehi.html" class="sb_item">Все</a>
                            <a href="/kupit-orehi/?filtr=raw" class="sb_item">Сырые</a>
                            <a href="/kupit-orehi/?filtr=roasted" class="sb_item">Жареные</a>
                            <a href="/kupit-orehi/?filtr=peeled" class="sb_item">Очищенные</a>
                            <a href="/kupit-orehi/?filtr=inshell" class="sb_item">В скорлупе</a>
                        </div>
                    </div>
                </div>

                <div class="sort_block">
                    <span>Сортировать:</span>
                    <div class="select_block">
                        <span class="this_item sb_item_icon ">По популярности</span>
                        <div class="sb_items">
                            <a href="/kupit-orehi/?sort[name]=ASC&" class="sb_item">По алфавиту (а-я)</a>
                            <a href="/kupit-orehi/?sort[name]=DESC&" class="sb_item">По алфавиту (я-а)</a>
                            <a href="/kupit-orehi/?sort[pop]=DESC&" class="sb_item">По популярности (убыв)</a>
                            <a href="/kupit-orehi/?sort[pop]=ASC&" class="sb_item">По популярности (возр)</a>
                        </div>

                    </div>
                </div>
            </div>-->

            <!--<div id="sort_block" class="nav_panel hide shows_sf show_this">
                <div class="item_title display-mob"><span class="title">Сортировка по: </span></div>
                <div class="list">
                    <div class="item_title"><span class="title">Сортировка по: </span></div>
                    &lt;!&ndash; <div class="item selected up"> &ndash;&gt;

                    <div class="item  up">
                        <a href="/kupit-orehi/?sort[name]=ASC&">Алфавиту</a>
                    </div>

                    <div class="item selected up">
                        <a href="/kupit-orehi/?sort[pop]=ASC&">Популярности</a>
                        <i class="icon-arrow-down"></i>
                    </div>

                </div>
            </div>-->


            <!--<div id="show_filter" class="nav_panel hide shows_sf ">
                <div class="item_title display-mob"><span class="title">Фильтр: </span></div>
                <div class="list">
                    <div class="item_title"><span class="title">Фильтр: </span></div>
                    &lt;!&ndash; <div class="item selected up"> &ndash;&gt;
                    <div class="item selected">
                        <a href="kupit-orehi.html">Все</a>
                    </div>

                    <div class="item ">
                        <a href="/kupit-orehi/?filtr=raw">Сырые</a>
                    </div>
                    <div class="item ">
                        <a href="/kupit-orehi/?filtr=roasted">Жареные</a>
                    </div>

                    <div class="item ">
                        <a href="/kupit-orehi/?filtr=peeled">Очищенные</a>
                    </div>
                    <div class="item ">
                        <a href="/kupit-orehi/?filtr=inshell">В скорлупе</a>
                    </div>
                </div>
            </div>-->

            {% if products %}
                <div class="thumbs">
                    {% for product in products %}
                        {% include "shop/product/card.html" with product=product %}
                    {% endfor %}
                </div>
            {% else %}
                <p>Список продуктов пуст</p>
            {% endif %}

            <!--<div class="pagination " style="border:0;">
                <div class="pager">
                    <div class="item default ?">
                        <i class="icon-arrow-left"></i>
                    </div>

                    <div class="item selected">
                        <span>1</span>
                    </div>
                    <div class="item ">
                        <a href="/kupit-orehi/?page=2">2</a>
                    </div>


                    <div class="item default">
                        <a href="/kupit-orehi/?page=2"><i class="icon-arrow-right"></i></a>
                    </div>


                    <div class="more desctop_only">
                        <a href="/kupit-orehi/?all=show">Просмотреть все</a>
                    </div>


                </div>
                <div class="more pagin_mobile">
                    <a href="/kupit-orehi/?all=show">Просмотреть все</a>
                </div>
            </div>-->
        </div>
    </div>
{% endblock %}

app/shop/templates/shop/product/search_results.html
{% extends 'shop/base.html' %}
{% load static %}

{% block head %}
    <title>Результаты поиска</title>
    <meta name="description" content="" />
{% endblock %}

{% block body %}
    <div class="breadcrumbs">
        <div class="container">
            <ul class="breadcrumbs_list">
                <li class="item">
                    <a href="/">
                        <span>Главная</span>
                    </a>
                </li>
                <li class="item">
                    <a href="/all-foods">
                        <span>Интернет-магазин</span>
                    </a>
                </li>
                <li class="item">
                    <span>Поиск</span>
                </li>
            </ul>
        </div>
    </div>

    <div class="main_block">
        <div class="container">
            {% if query %}
                <div class="headline">
                    <h1 class="title">Результаты поиска: {{ query }}</h1>
                </div>
            {% endif %}
            {% comment %}<div class="nav_panel">
                <div class="list">
                    <div class="item_title"><span class="title">Сортировка: </span></div>
                    <!-- <div class="item selected up"> -->

                    <div class="item  down">
                        <a href="/search/?q=орех&sort[name]=DESC">По алфавиту</a>
                    </div>
                    <div class="item selected up">
                        <a href="/search/?q=орех&sort[pop]=ASC">Популярности</a>
                        <i class="icon-arrow-down"></i>
                    </div>

                </div>
            </div>{% endcomment %}

            {% if products %}
                <div class="thumbs">
                    {% for product in products %}
                        {% include "shop/product/card.html" with product=product %}
                    {% endfor %}
                </div>
            {% else %}
                <p>По вашему запросу "{{ query }}" ничего не найдено</p>
            {% endif %}

            {% comment %}<div class="pagination">
                <div class="pager">
                    <div class="item default ?">
                        <i class="icon-arrow-left"></i>
                    </div>
                    <div class="item selected">
                        <span>1</span>
                    </div>
                    <div class="item ">
                        <a href="/search/?q=орех&p=2">2</a>
                    </div>
                    <div class="item default">
                        <a href="/search/?q=орех&p=2"><i class="icon-arrow-right"></i></a>
                    </div>
                </div>
            </div>{% endcomment %}
        </div>
    </div>
{% endblock %}